<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="lidar_length" value="0.05" />
  <xacro:property name="lidar_radius" value="0.05" />

  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}" />
      </geometry>
      <material name="grey" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}" />
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="0.1" r="${lidar_radius}" h="${lidar_length}" xyz="0 0 0" rpy="0 0 0" />
  </link>

  <joint name="base_lidar_joint" type="fixed">
    <parent link="base_link" />
    <child link="lidar_link" />
    <origin xyz="0 0 ${base_height + lidar_length / 2}" rpy="0 0 0" />
  </joint>
   
  <gazebo reference="lidar_link">
    <material>Gazebo/Purple</material>
    <sensor name="lidar" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.3</min>
          <max>12</max>
        </range>
      </ray>
      <plugin name="lidar_controller" filename="libgazebo_ros_ray_sensor.so">
      <ros>
        <remapping>~/out:=scan</remapping>
      </ros>
      <output_type>sensor_msgs/LaserScan</output_type>
      <frame_name>lidar_frame</frame_name>
      </plugin>
    </sensor>
  </gazebo>

</robot>
