velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [100.5, 0.0, 400.0]  # Adjusted maximum linear and angular velocities
    min_velocity: [-100.5, 0.0, -400.0]  # Adjusted minimum linear and angular velocities
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
    max_accel: [30.0, 0.0, 60.0]  # Adjusted maximum linear and angular accelerations
    max_decel: [-30.0, 0.0, -60.0]  # Adjusted maximum linear and angular decelerations
    odom_topic: "odom"
    odom_duration: 0.1
    use_realtime_priority: false
    enable_stamped_cmd_vel: false

